'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {start,staff,uid}=require('./helpers');
test('athlete progress, coach follow-ups, and question review preserve records and permissions',async t=>{
 const s=await start();t.after(s.close);const {coach,coach2}=await staff(s);
 const made=(await coach.post('/api/athletes',{name:'Measured athlete',sport:'Football',dash_15_seconds:2.8})).body;
 const aid=made.athlete.id,p=s.client();await p.signup('Measured athlete','measured@lab.test');assert.equal((await p.post('/api/claim',{code:made.claim_code})).status,200);
 const path='/api/athletes/'+aid+'/progress';
 let history=(await p.get(path)).body;assert.equal(history.measurements.length,1);assert.equal(history.measurements[0].values.dash_15_seconds,2.8);
 const result={id:uid(),date:'2026-09-29',values:{sport:'Football',dash_15_seconds:2.65,vertical_inches:30},notes:'Electronic timing',retestOn:'2026-10-29'};
 assert.equal((await p.post(path,result)).status,200);assert.equal((await p.post(path,result)).status,200);
 assert.equal((await p.post(path,{...result,notes:'Changed'})).status,409);
 assert.equal((await coach2.get(path)).status,404);
 assert.equal((await p.post(path,{...result,id:uid(),values:{dash_15_seconds:-1}})).status,400);
 assert.equal((await p.post(path,{...result,id:uid(),date:'2026-02-31'})).status,400);
 history=(await p.get(path)).body;assert.equal(history.measurements.length,2);
 const task={id:uid(),athleteId:aid,title:'Review retest',due:'2026-10-29',assignee:'',status:'open',revision:0};
 assert.equal((await coach.post('/api/coach/followups',task)).status,200);
 assert.equal((await coach.post('/api/coach/followups',task)).status,200);
 assert.equal((await p.get('/api/coach/followups')).status,403);
 assert.equal((await coach2.post('/api/coach/followups',task)).status,404);
 assert.equal((await coach.post('/api/coach/followups',{...task,status:'done',revision:1})).status,200);
 assert.equal((await coach.post('/api/coach/followups',{...task,title:'Stale',revision:1})).status,409);
 const question=(await p.post('/api/athletes/'+aid+'/notes',{body:'Question\nHow can I improve my start?',client_id:uid()})).body;
 let queue=(await coach.get('/api/coach/followups')).body;assert(queue.notes.some(n=>n.id===question.id));
 const reply={body:'Stay balanced through your first step.',client_id:uid()};
 assert.equal((await coach2.post('/api/notes/'+question.id+'/reply',reply)).status,404);
 assert.equal((await coach.post('/api/notes/'+question.id+'/reply',reply)).status,200);
 assert.equal((await coach.post('/api/notes/'+question.id+'/reply',reply)).status,200);
 queue=(await coach.get('/api/coach/followups')).body;assert(!queue.notes.some(n=>n.id===question.id));
 const profile=(await p.get('/api/athletes/'+aid)).body;assert.equal(profile.notes.filter(n=>n.reply_to===question.id).length,1);assert.equal(profile.notes.find(n=>n.reply_to===question.id).body,reply.body);
});
