/* One read-only history over existing, permission-checked app and website records. */
(function(){'use strict';
 window.LabPlugins=window.LabPlugins||[];
 window.LabPlugins.push(function(ctx){
  const L=window.Lab,h=L.h,api=L.api,root=()=>document.getElementById('app');
  const labels={session:'Session',event:'Event',media:'Video / photo',note:'Coaching note',question:'Question',reflection:'Reflection',feedback:'Feedback',training:'Training',checkin:'Check-in',development:'Development Block',communication:'Notification'};
  const date=v=>{const d=new Date(v.length===10?v+'T12:00:00':v);return isNaN(d)?'Date unavailable':d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});};
  ctx.routes.push([/^\/timeline(?:\/(app|website)\/([^/]+))?$/,'playerTimeline','home']);
  ctx.views.playerTimeline=async function(source,_params,id){
   const query=new URLSearchParams();if(id)query.set(source==='website'?'website':'athlete',id);
   const host=document.createElement('div');host.className='journey lab-history';root().replaceChildren(host);
   host.innerHTML='<header class="journey-heading"><div><p class="eyebrow">THE LAB / PLAYER DEVELOPMENT</p><h1>Everything that moves the player forward.</h1><p id="history-name">Loading the complete athlete story…</p></div><div class="row"><button class="btn" id="history-refresh">Refresh</button><a class="btn primary" href="'+(id?(source==='website'?'#/workspace/athlete/':'#/coach/')+encodeURIComponent(id):'#/journey/feedback')+'">'+(id?'Open player workspace':'Ask & upload')+'</a></div></header><div class="history-answers"><div><span>WHAT HAPPENED?</span><b id="answer-latest">Loading…</b></div><div><span>CURRENT WORK</span><b id="answer-focus">Loading…</b></div><div><span>NEEDS A RESPONSE</span><b id="answer-response">Loading…</b></div><div><span>WHAT HAPPENS NEXT?</span><b id="answer-next">Loading…</b></div></div><div class="history-status" id="history-status" aria-live="polite"></div><div class="history-controls"><label>Find in loaded history<input type="search" id="history-search" placeholder="Search sessions, cues, questions…"></label><div class="chips" id="history-filter"><button class="chip" data-filter="all" aria-pressed="true">All</button><button class="chip" data-filter="upcoming">Upcoming</button><button class="chip" data-filter="sessions">Sessions</button><button class="chip" data-filter="coaching">Coaching</button><button class="chip" data-filter="media">Media</button><button class="chip" data-filter="communication">Communication</button></div></div><p class="small muted" id="history-count"></p><div id="history-content"></div><div class="row" id="history-more"></div><p class="small muted">Records stay in their original systems. Private items appear only to authorized coaches and are marked Coach only.</p>';
   const state={app:{items:[],next:null,status:'loading'},website:{items:[],next:null,status:'loading'}};
   let loading=false;
   const el=s=>host.querySelector(s);
   function paint(){
    const items=Object.values(state).flatMap(s=>s.items),term=el('#history-search').value.toLowerCase().trim(),filter=host.querySelector('#history-filter [aria-pressed="true"]')?.dataset?.filter||el('#history-filter').value||'all';
    const duplicates=new Set();const signatures=new Map();for(const i of items){if(!i.body||i.body.trim().length<15)continue;const signature=[i.kind,i.at.slice(0,10),i.body.toLowerCase().replace(/\s+/g,' ').trim()].join('|');const prior=signatures.get(signature);if(prior&&prior.source!==i.source){duplicates.add(i.id);duplicates.add(prior.id);}else signatures.set(signature,i);}
    const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
    const next=i=>(['session','event'].includes(i.kind)&&!['complete','completed','reviewed','cancelled'].includes(i.status)&&(i.status==='live'||i.at.slice(0,10)>=today))||(i.kind==='training'&&['open','next','progress','approved'].includes(i.status));
    const bucket=(i,f)=>f==='all'||f==='upcoming'&&next(i)||f==='sessions'&&['session','event'].includes(i.kind)||f==='coaching'&&['note','training','development'].includes(i.kind)||f==='media'&&i.kind==='media'||f==='communication'&&['question','reflection','feedback','checkin','communication'].includes(i.kind)||i.kind===f;
    const selected=items.filter(i=>bucket(i,filter)&&(!term||[i.title,i.body,i.status].join(' ').toLowerCase().includes(term))).sort((a,b)=>b.at.localeCompare(a.at)||b.id.localeCompare(a.id));
    const upcoming=selected.filter(next).sort((a,b)=>(a.due||a.at).localeCompare(b.due||b.at)),past=selected.filter(i=>!next(i));
    function card(i){
     let media='';if(i.media){const m=i.media;const url=i.source==='app'?'/api/media/'+encodeURIComponent(m.id):'/api/timeline/media?'+new URLSearchParams({...Object.fromEntries(query),kind:m.kind,id:m.id});media='<div class="history-media">'+(m.mime.startsWith('video/')?'<video controls playsinline preload="none" aria-label="'+h(i.title)+'" src="'+h(url)+'"></video>':'<img loading="lazy" src="'+h(url)+'" alt="'+h(i.title)+'">')+'<a href="'+h(url)+'" target="_blank" rel="noopener">Open attachment</a><p class="small muted" data-media-error hidden>Attachment could not load. Refresh your connection, then try Open attachment.</p></div>';}
     return '<article class="history-entry'+(i.private?' private':'')+'" id="'+h(i.id)+'"><div class="history-date"><time>'+h(date(i.at))+'</time><span>'+h(i.source==='app'?'App':'Website')+'</span></div><div class="history-card"><div class="journey-meta"><span class="tag">'+h(labels[i.kind]||i.kind)+'</span>'+(i.private?'<span class="tag">Coach only</span>':'')+(i.status&&!i.private?'<span>'+h(i.status)+'</span>':'')+'</div><h3>'+h(i.title)+'</h3>'+(i.due?'<p class="small">'+(i.due.slice(0,10)<today&&!['done','resolved','complete','completed'].includes(i.status)?'Past date · ':'')+'Scheduled / due '+h(date(i.due))+'</p>':'')+(i.body?'<p class="journey-copy history-copy">'+h(i.body)+'</p>':'')+media+(duplicates.has(i.id)?'<p class="history-duplicate">Possible matching entry in the other system. Both originals are preserved.</p>':'')+(i.href?'<a class="btn" href="'+h(i.href)+'">Open record</a>':'')+'</div></article>';
    }
    el('#history-content').innerHTML=(upcoming.length?'<section><h2>Up next & in progress</h2>'+upcoming.map(card).join('')+'</section>':'')+(past.length?'<section><h2>The work so far</h2>'+past.map(card).join('')+'</section>':'')+(!selected.length?'<div class="journey-empty"><h3>'+(loading?'Loading your history…':'No entries to show yet.')+'</h3><p>'+(term||filter!=='all'?'Try another filter or load older entries.':'Connected sessions, shared notes, media and feedback appear here. Check each connection above.')+'</p></div>':'');
    host.querySelectorAll('video,img').forEach(m=>m.addEventListener('error',()=>{m.parentElement.querySelector('[data-media-error]').hidden=false;}));
    el('#history-count').textContent=selected.length+' shown · '+items.length+' loaded'+(Object.values(state).some(s=>s.next)?' · Older records available':'');
    const ordered=[...items].sort((a,b)=>b.at.localeCompare(a.at)),waiting=items.filter(i=>['question','reflection','checkin'].includes(i.kind)&&!['Reviewed','planned','complete'].includes(i.status)),nextItems=items.filter(next).sort((a,b)=>(a.due||a.at).localeCompare(b.due||b.at));
    el('#answer-latest').textContent=ordered[0]?.title||'No activity yet';el('#answer-focus').textContent=ordered.find(i=>['development','training'].includes(i.kind)&&!['done','mastered','complete'].includes(i.status))?.title||'No active focus';el('#answer-response').textContent=waiting.length?waiting.length+' item'+(waiting.length===1?'':'s')+' waiting':'Nothing waiting';el('#answer-next').textContent=nextItems[0]?.title||'Set the next action';
    el('#history-status').innerHTML=Object.entries(state).map(([key,s])=>'<div class="history-source '+(s.status==='error'?'history-warning':'')+'"><b>'+h(key==='app'?'App history':'Website history')+'</b><span>'+h(s.status==='ok'?s.items.length+' entries loaded · checked '+new Date(s.checkedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):s.message||'Loading…')+'</span>'+(s.status==='unlinked'&&!id?'<a href="'+(key==='website'?'/api/site-bridge/signin/start':'#/profile')+'">Connect profile</a>':'')+(s.status==='error'?'<button class="btn" data-retry="'+key+'">Retry connection</button>':'')+'</div>').join('');
    el('#history-more').innerHTML=Object.entries(state).filter(([,s])=>s.next).map(([key])=>'<button class="btn" data-older="'+key+'" '+(loading?'disabled':'')+'>Load older '+(key==='app'?'app':'website')+' records</button>').join('');
    host.querySelectorAll('[data-older]').forEach(b=>b.onclick=()=>load(b.dataset.older,true));host.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>load(b.dataset.retry,false));
   }
   async function load(only,older=false){if(loading)return;loading=true;el('#history-refresh').disabled=true;paint();const q=new URLSearchParams(query);if(only)q.set('source',only);if(older)q.set(only==='app'?'appBefore':'webBefore',state[only].next);
    try{const d=await api.request('GET','/api/timeline?'+q);if(!host.isConnected)return;el('#history-name').textContent=d.athlete.name+' · Sessions, videos, notes and conversations';for(const [k,s] of Object.entries(d.sources)){if(s.status==='ok'){const merged=older?[...state[k].items,...s.items]:s.items;state[k]={...s,items:[...new Map(merged.map(i=>[i.id,i])).values()]};}else state[k]={...state[k],status:s.status,message:s.message+(state[k].items.length?' Previously loaded entries may be out of date.':'')};}}
    catch(e){if(!host.isConnected)return;for(const k of only?[only]:['app','website'])state[k]={...state[k],status:'error',message:e.message};}
    finally{loading=false;if(host.isConnected){el('#history-refresh').disabled=false;paint();}}
   }
   el('#history-search').oninput=paint;el('#history-filter').onchange=paint;host.querySelectorAll('#history-filter button').forEach(b=>b.onclick=()=>{host.querySelectorAll('#history-filter button').forEach(x=>x.setAttribute('aria-pressed',x===b?'true':'false'));paint();});el('#history-refresh').onclick=()=>load();await load();
  };
  // Keep the combined history one tap away from both personal and coach views.
  for(const name of ['home','profile','coachAthlete','workspaceAthlete']){const original=ctx.views[name];if(!original)continue;ctx.views[name]=async function(...args){const hash=location.hash;await original(...args);if(location.hash!==hash)return;const match=hash.match(/^#\/(?:workspace\/athlete|coach)\/([^/?]+)/),website=hash.startsWith('#/workspace/athlete/');const href=match?'#/timeline/'+(website?'website':'app')+'/'+encodeURIComponent(match[1]):'#/timeline';const row=document.createElement('div');row.className='history-launch';row.innerHTML='<a class="btn" href="'+href+'">Open player timeline</a><span>Sessions · Videos · Notes · Feedback</span>';root().prepend(row);};}
 });
})();
